---
kind: pipeline
name: e2e-kubernetes-1.16

platform:
  os: linux
  arch: amd64

steps:
  - name: init
    image: quay.io/sighup/e2e-testing-drone-plugin:v0.2.1
    pull: always
    volumes:
    - name: shared
      path: /shared
    depends_on: [ clone ]
    settings:
      action: custom-cluster-116
      pipeline_id: cluster-116
      local_kind_config_path: katalog/tests/config/kind-config-custom
      cluster_version: '1.16.4'
      instance_path: /shared
      aws_default_region:
        from_secret: aws_region
      aws_access_key_id:
        from_secret: aws_access_key_id
      aws_secret_access_key:
        from_secret: aws_secret_access_key
      terraform_tf_states_bucket_name:
        from_secret: terraform_tf_states_bucket_name
    when:
      ref:
        include:
          - refs/heads/hotfix-*
          - refs/tags/**

  - name: test
    image: quay.io/sighup/e2e-testing:1.1.0_0.2.2_2.16.1_1.4.0_1.16.4_3.2.2_2.4.1
    pull: always
    volumes:
    - name: shared
      path: /shared
    depends_on: [ init ]
    commands:
      - export KUBECONFIG=/shared/kube/kubeconfig-116
      - bats -t katalog/tests/install.sh
      - bats -t katalog/tests/networking.sh
      - bats -t katalog/tests/monitoring.sh
      - bats -t katalog/tests/logging.sh
      - bats -t katalog/tests/ingress.sh
      - bats -t katalog/tests/dr.sh
    when:
      ref:
        include:
          - refs/heads/hotfix-*
          - refs/tags/**

  - name: prepare-release-notes
    image: python:3.7
    pull: always
    depends_on: [ test ]
    environment:
      RELEASE_NOTES_FILE_PATH: release-notes.md
    commands:
      - pip install semantic_version==2.8.4
      - python -u release-notes.py
    when:
      ref:
        include:
          - refs/tags/**

  - name: publish-prerelease
    image: plugins/github-release
    pull: always
    depends_on: [ test ]
    settings:
      api_key:
        from_secret: github_token
      files:
        - Furyfile.yml
        - kustomization.yaml
      prerelease: true
      overwrite: true
      title: "Prerelease ${DRONE_TAG}"
      checksum:
        - md5
        - sha256
    when:
      ref:
        include:
          - refs/tags/v**-rc**

  - name: publish-stable
    image: plugins/github-release
    pull: always
    depends_on: [ prepare-release-notes ]
    settings:
      api_key:
        from_secret: github_token
      files:
        - Furyfile.yml
        - kustomization.yaml
      prerelease: false
      overwrite: true
      title: "Release ${DRONE_TAG}"
      note: release-notes.md
      checksum:
        - md5
        - sha256
    when:
      ref:
        exclude:
          - refs/tags/v**-rc**
        include:
          - refs/tags/v**

  - name: destroy
    image: quay.io/sighup/e2e-testing-drone-plugin:v0.2.1
    pull: always
    depends_on: [ test ]
    settings:
      action: destroy
      pipeline_id: cluster-116
      aws_default_region:
        from_secret: aws_region
      aws_access_key_id:
        from_secret: aws_access_key_id
      aws_secret_access_key:
        from_secret: aws_secret_access_key
      terraform_tf_states_bucket_name:
        from_secret: terraform_tf_states_bucket_name
    when:
      status:
      - success
      - failure

volumes:
- name: shared
  temp: {}

---
kind: pipeline
name: e2e-kubernetes-1.15

platform:
  os: linux
  arch: amd64

steps:
  - name: init
    image: quay.io/sighup/e2e-testing-drone-plugin:v0.2.1
    pull: always
    volumes:
    - name: shared
      path: /shared
    depends_on: [ clone ]
    settings:
      action: custom-cluster-115
      pipeline_id: cluster-115
      local_kind_config_path: katalog/tests/config/kind-config-custom
      cluster_version: '1.15.7'
      instance_path: /shared
      aws_default_region:
        from_secret: aws_region
      aws_access_key_id:
        from_secret: aws_access_key_id
      aws_secret_access_key:
        from_secret: aws_secret_access_key
      terraform_tf_states_bucket_name:
        from_secret: terraform_tf_states_bucket_name
    when:
      ref:
        include:
          - refs/heads/hotfix-*
          - refs/tags/**

  - name: test
    image: quay.io/sighup/e2e-testing:1.1.0_0.2.2_2.16.1_1.4.0_1.15.7_3.2.2_2.4.1
    pull: always
    volumes:
    - name: shared
      path: /shared
    depends_on: [ init ]
    commands:
      - export KUBECONFIG=/shared/kube/kubeconfig-115
      - bats -t katalog/tests/install.sh
      - bats -t katalog/tests/networking.sh
      - bats -t katalog/tests/monitoring.sh
      - bats -t katalog/tests/logging.sh
      - bats -t katalog/tests/ingress.sh
      - bats -t katalog/tests/dr.sh
    when:
      ref:
        include:
          - refs/heads/hotfix-*
          - refs/tags/**

  - name: prepare-release-notes
    image: python:3.7
    pull: always
    depends_on: [ test ]
    environment:
      RELEASE_NOTES_FILE_PATH: release-notes.md
    commands:
      - pip install semantic_version==2.8.4
      - python -u release-notes.py
    when:
      ref:
        include:
          - refs/tags/**

  - name: publish-prerelease
    image: plugins/github-release
    pull: always
    depends_on: [ test ]
    settings:
      api_key:
        from_secret: github_token
      files:
        - Furyfile.yml
        - kustomization.yaml
      prerelease: true
      overwrite: true
      title: "Prerelease ${DRONE_TAG}"
      checksum:
        - md5
        - sha256
    when:
      ref:
        include:
          - refs/tags/v**-rc**

  - name: publish-stable
    image: plugins/github-release
    pull: always
    depends_on: [ prepare-release-notes ]
    settings:
      api_key:
        from_secret: github_token
      files:
        - Furyfile.yml
        - kustomization.yaml
      prerelease: false
      overwrite: true
      title: "Release ${DRONE_TAG}"
      note: release-notes.md
      checksum:
        - md5
        - sha256
    when:
      ref:
        exclude:
          - refs/tags/v**-rc**
        include:
          - refs/tags/v**

  - name: destroy
    image: quay.io/sighup/e2e-testing-drone-plugin:v0.2.1
    pull: always
    depends_on: [ test ]
    settings:
      action: destroy
      pipeline_id: cluster-115
      aws_default_region:
        from_secret: aws_region
      aws_access_key_id:
        from_secret: aws_access_key_id
      aws_secret_access_key:
        from_secret: aws_secret_access_key
      terraform_tf_states_bucket_name:
        from_secret: terraform_tf_states_bucket_name
    when:
      status:
      - success
      - failure

volumes:
- name: shared
  temp: {}
---
kind: pipeline
name: e2e-kubernetes-1.14

platform:
  os: linux
  arch: amd64

steps:
  - name: init
    image: quay.io/sighup/e2e-testing-drone-plugin:v0.2.1
    pull: always
    volumes:
    - name: shared
      path: /shared
    depends_on: [ clone ]
    settings:
      action: custom-cluster-114
      pipeline_id: cluster-114
      local_kind_config_path: katalog/tests/config/kind-config-custom
      cluster_version: '1.14.10'
      instance_path: /shared
      aws_default_region:
        from_secret: aws_region
      aws_access_key_id:
        from_secret: aws_access_key_id
      aws_secret_access_key:
        from_secret: aws_secret_access_key
      terraform_tf_states_bucket_name:
        from_secret: terraform_tf_states_bucket_name
    when:
      ref:
        include:
          - refs/heads/hotfix-*
          - refs/tags/**

  - name: test
    image: quay.io/sighup/e2e-testing:1.1.0_0.2.2_2.16.1_1.4.0_1.14.10_3.2.2_2.4.1
    pull: always
    volumes:
    - name: shared
      path: /shared
    depends_on: [ init ]
    commands:
      - export KUBECONFIG=/shared/kube/kubeconfig-114
      - bats -t katalog/tests/install.sh
      - bats -t katalog/tests/networking.sh
      - bats -t katalog/tests/monitoring.sh
      - bats -t katalog/tests/logging.sh
      - bats -t katalog/tests/ingress.sh
      - bats -t katalog/tests/dr.sh
    when:
      ref:
        include:
          - refs/heads/hotfix-*
          - refs/tags/**

  - name: prepare-release-notes
    image: python:3.7
    pull: always
    depends_on: [ test ]
    environment:
      RELEASE_NOTES_FILE_PATH: release-notes.md
    commands:
      - pip install semantic_version==2.8.4
      - python -u release-notes.py
    when:
      ref:
        include:
          - refs/tags/**

  - name: publish-prerelease
    image: plugins/github-release
    pull: always
    depends_on: [ prepare-release-notes ]
    settings:
      api_key:
        from_secret: github_token
      files:
        - Furyfile.yml
        - kustomization.yaml
      prerelease: true
      overwrite: true
      title: "Prerelease ${DRONE_TAG}"
      note: release-notes.md
      checksum:
        - md5
        - sha256
    when:
      ref:
        include:
          - refs/tags/v**-rc**

  - name: publish-stable
    image: plugins/github-release
    pull: always
    depends_on: [ prepare-release-notes ]
    settings:
      api_key:
        from_secret: github_token
      files:
        - Furyfile.yml
        - kustomization.yaml
      prerelease: false
      overwrite: true
      title: "Release ${DRONE_TAG}"
      note: release-notes.md
      checksum:
        - md5
        - sha256
    when:
      ref:
        exclude:
          - refs/tags/v**-rc**
        include:
          - refs/tags/v**

  - name: destroy
    image: quay.io/sighup/e2e-testing-drone-plugin:v0.2.1
    pull: always
    depends_on: [ test ]
    settings:
      action: destroy
      pipeline_id: cluster-114
      aws_default_region:
        from_secret: aws_region
      aws_access_key_id:
        from_secret: aws_access_key_id
      aws_secret_access_key:
        from_secret: aws_secret_access_key
      terraform_tf_states_bucket_name:
        from_secret: terraform_tf_states_bucket_name
    when:
      status:
      - success
      - failure

volumes:
- name: shared
  temp: {}
