bases:
  # Networking
  - ./vendor/katalog/networking/calico
  # Monitoring
  - ./vendor/katalog/monitoring/prometheus-operator
  - ./vendor/katalog/monitoring/prometheus-operated
  - ./vendor/katalog/monitoring/grafana
  - ./vendor/katalog/monitoring/goldpinger
  - ./vendor/katalog/monitoring/kubeadm-sm
  - ./vendor/katalog/monitoring/kube-state-metrics
  - ./vendor/katalog/monitoring/node-exporter
  # Logging
  - ./vendor/katalog/logging/elasticsearch-single
  - ./vendor/katalog/logging/cerebro
  - ./vendor/katalog/logging/curator
  - ./vendor/katalog/logging/fluentd
  - ./vendor/katalog/logging/kibana
  # Ingress
  - ./vendor/katalog/ingress/cert-manager
  - ./vendor/katalog/ingress/nginx
  - ./vendor/katalog/ingress/forecastle
  # DR
  - ./vendor/katalog/dr/velero/velero-on-prem
  - ./vendor/katalog/dr/velero/velero-restic
